// Dummy product images using placeholder services
const placeholderImage = (w, h, text) =>
  `https://placehold.co/${w}x${h}/e5e5e5/737373?text=${encodeURIComponent(text)}`;

export const products = [
  {
    id: 1,
    slug: 'classic-oxford-shirt',
    name: 'Classic Oxford Shirt',
    brand: 'FASHION STORE',
    price: 1999,
    originalPrice: 3499,
    discount: 43,
    category: 'shirts',
    description: 'A timeless oxford shirt crafted from premium cotton. Features a button-down collar, chest pocket, and a relaxed fit that transitions seamlessly from office to weekend.',
    images: [
      placeholderImage(600, 800, 'Oxford+Shirt+1'),
      placeholderImage(600, 800, 'Oxford+Shirt+2'),
      placeholderImage(600, 800, 'Oxford+Shirt+3'),
      placeholderImage(600, 800, 'Oxford+Shirt+4'),
    ],
    colors: [
      { name: 'White', hex: '#FFFFFF' },
      { name: 'Light Blue', hex: '#A8D8EA' },
      { name: 'Pink', hex: '#F5C6C6' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    unavailableSizes: ['XXL'],
    fabric: '100% Premium Cotton',
    rating: 4.5,
    reviewCount: 128,
    badges: ['bestseller'],
    isNew: false,
    isTrending: true,
  },
  {
    id: 2,
    slug: 'slim-fit-chinos',
    name: 'Slim Fit Chinos',
    brand: 'FASHION STORE',
    price: 1499,
    originalPrice: 2499,
    discount: 40,
    category: 'trousers',
    description: 'Modern slim-fit chinos made from stretch cotton twill. Perfect for casual Fridays and weekend outings, featuring a comfortable mid-rise waist.',
    images: [
      placeholderImage(600, 800, 'Chinos+1'),
      placeholderImage(600, 800, 'Chinos+2'),
      placeholderImage(600, 800, 'Chinos+3'),
    ],
    colors: [
      { name: 'Beige', hex: '#D4B896' },
      { name: 'Navy', hex: '#1B2A4A' },
      { name: 'Olive', hex: '#5C6B4F' },
    ],
    sizes: ['28', '30', '32', '34', '36', '38'],
    unavailableSizes: [],
    fabric: '98% Cotton, 2% Elastane',
    rating: 4.3,
    reviewCount: 95,
    badges: [],
    isNew: false,
    isTrending: false,
  },
  {
    id: 3,
    slug: 'oversized-graphic-tee',
    name: 'Oversized Graphic Tee',
    brand: 'FASHION STORE',
    price: 899,
    originalPrice: 1499,
    discount: 40,
    category: 't-shirts',
    description: 'A street-style essential oversized graphic tee with a vintage-inspired print. Made from soft organic cotton with a dropped shoulder design.',
    images: [
      placeholderImage(600, 800, 'Graphic+Tee+1'),
      placeholderImage(600, 800, 'Graphic+Tee+2'),
    ],
    colors: [
      { name: 'Black', hex: '#0A0A0A' },
      { name: 'White', hex: '#FFFFFF' },
      { name: 'Charcoal', hex: '#36454F' },
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    unavailableSizes: [],
    fabric: '100% Organic Cotton',
    rating: 4.7,
    reviewCount: 234,
    badges: ['new'],
    isNew: true,
    isTrending: true,
  },
  {
    id: 4,
    slug: 'leather-bomber-jacket',
    name: 'Leather Bomber Jacket',
    brand: 'FASHION STORE',
    price: 5999,
    originalPrice: 8999,
    discount: 33,
    category: 'jackets',
    description: 'Premium faux leather bomber jacket with a quilted lining. Features ribbed cuffs and hem, zippered pockets, and a classic silhouette.',
    images: [
      placeholderImage(600, 800, 'Bomber+1'),
      placeholderImage(600, 800, 'Bomber+2'),
      placeholderImage(600, 800, 'Bomber+3'),
    ],
    colors: [
      { name: 'Black', hex: '#0A0A0A' },
      { name: 'Brown', hex: '#8B4513' },
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    unavailableSizes: ['XL'],
    fabric: 'PU Leather, Polyester Lining',
    rating: 4.8,
    reviewCount: 67,
    badges: ['trending'],
    isNew: false,
    isTrending: true,
  },
  {
    id: 5,
    slug: 'linen-summer-shirt',
    name: 'Linen Summer Shirt',
    brand: 'FASHION STORE',
    price: 1799,
    originalPrice: 2999,
    discount: 40,
    category: 'shirts',
    description: 'Breathable linen shirt perfect for summer. Features a relaxed fit with a spread collar and rolled-up sleeve tabs.',
    images: [
      placeholderImage(600, 800, 'Linen+Shirt+1'),
      placeholderImage(600, 800, 'Linen+Shirt+2'),
    ],
    colors: [
      { name: 'White', hex: '#FFFFFF' },
      { name: 'Sky Blue', hex: '#87CEEB' },
      { name: 'Sage', hex: '#B2AC88' },
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    unavailableSizes: [],
    fabric: '100% French Linen',
    rating: 4.6,
    reviewCount: 156,
    badges: ['new'],
    isNew: true,
    isTrending: false,
  },
  {
    id: 6,
    slug: 'jogger-pants',
    name: 'Tech Jogger Pants',
    brand: 'FASHION STORE',
    price: 1299,
    originalPrice: 1999,
    discount: 35,
    category: 'trousers',
    description: 'Performance-meets-style jogger pants with moisture-wicking fabric. Features zippered pockets and an elastic waistband with drawstring.',
    images: [
      placeholderImage(600, 800, 'Joggers+1'),
      placeholderImage(600, 800, 'Joggers+2'),
    ],
    colors: [
      { name: 'Black', hex: '#0A0A0A' },
      { name: 'Gray', hex: '#808080' },
      { name: 'Navy', hex: '#1B2A4A' },
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    unavailableSizes: [],
    fabric: '92% Polyester, 8% Spandex',
    rating: 4.4,
    reviewCount: 89,
    badges: [],
    isNew: false,
    isTrending: false,
  },
  {
    id: 7,
    slug: 'denim-jacket-classic',
    name: 'Classic Denim Jacket',
    brand: 'FASHION STORE',
    price: 2499,
    originalPrice: 3999,
    discount: 38,
    category: 'jackets',
    description: 'An iconic denim jacket in mid-wash indigo. Features button-front closure, chest flap pockets, and a slightly cropped fit.',
    images: [
      placeholderImage(600, 800, 'Denim+Jacket+1'),
      placeholderImage(600, 800, 'Denim+Jacket+2'),
    ],
    colors: [
      { name: 'Indigo', hex: '#3F5B8A' },
      { name: 'Light Wash', hex: '#A8C4D9' },
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    unavailableSizes: [],
    fabric: '100% Cotton Denim',
    rating: 4.5,
    reviewCount: 112,
    badges: [],
    isNew: false,
    isTrending: true,
  },
  {
    id: 8,
    slug: 'polo-knit-shirt',
    name: 'Knit Polo Shirt',
    brand: 'FASHION STORE',
    price: 1399,
    originalPrice: 2199,
    discount: 36,
    category: 'polo',
    description: 'Elevated knit polo shirt with a textured weave. Features a ribbed collar, two-button placket, and a regular fit.',
    images: [
      placeholderImage(600, 800, 'Polo+1'),
      placeholderImage(600, 800, 'Polo+2'),
    ],
    colors: [
      { name: 'Dark Green', hex: '#1B4332' },
      { name: 'Burgundy', hex: '#722F37' },
      { name: 'Navy', hex: '#1B2A4A' },
    ],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    unavailableSizes: ['XXL'],
    fabric: '100% Cotton Knit',
    rating: 4.2,
    reviewCount: 45,
    badges: [],
    isNew: false,
    isTrending: false,
  },
  {
    id: 9,
    slug: 'printed-cuban-shirt',
    name: 'Printed Cuban Shirt',
    brand: 'FASHION STORE',
    price: 1599,
    originalPrice: 2799,
    discount: 43,
    category: 'shirts',
    description: 'Resort-ready Cuban collar shirt with a vibrant tropical print. Features a relaxed fit and short sleeves.',
    images: [
      placeholderImage(600, 800, 'Cuban+Shirt+1'),
      placeholderImage(600, 800, 'Cuban+Shirt+2'),
    ],
    colors: [
      { name: 'Blue Print', hex: '#4A90D9' },
      { name: 'Black Print', hex: '#2D2D2D' },
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    unavailableSizes: [],
    fabric: '100% Viscose',
    rating: 4.6,
    reviewCount: 78,
    badges: ['trending'],
    isNew: false,
    isTrending: true,
  },
  {
    id: 10,
    slug: 'cargo-shorts',
    name: 'Urban Cargo Shorts',
    brand: 'FASHION STORE',
    price: 999,
    originalPrice: 1799,
    discount: 44,
    category: 'shorts',
    description: 'Versatile cargo shorts with utility pockets. Made from durable cotton canvas with a relaxed fit.',
    images: [
      placeholderImage(600, 800, 'Cargo+Shorts+1'),
      placeholderImage(600, 800, 'Cargo+Shorts+2'),
    ],
    colors: [
      { name: 'Khaki', hex: '#C3B091' },
      { name: 'Olive', hex: '#5C6B4F' },
      { name: 'Black', hex: '#0A0A0A' },
    ],
    sizes: ['28', '30', '32', '34', '36'],
    unavailableSizes: [],
    fabric: '100% Cotton Canvas',
    rating: 4.1,
    reviewCount: 56,
    badges: [],
    isNew: true,
    isTrending: false,
  },
  {
    id: 11,
    slug: 'knit-henley-tee',
    name: 'Knit Henley T-Shirt',
    brand: 'FASHION STORE',
    price: 799,
    originalPrice: 1299,
    discount: 38,
    category: 't-shirts',
    description: 'Classic henley neckline with a modern knitted texture. Perfect layering piece in soft cotton blend.',
    images: [
      placeholderImage(600, 800, 'Henley+1'),
      placeholderImage(600, 800, 'Henley+2'),
    ],
    colors: [
      { name: 'Cream', hex: '#FFFDD0' },
      { name: 'Black', hex: '#0A0A0A' },
      { name: 'Rust', hex: '#B7410E' },
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    unavailableSizes: [],
    fabric: '60% Cotton, 40% Polyester',
    rating: 4.3,
    reviewCount: 92,
    badges: [],
    isNew: false,
    isTrending: false,
  },
  {
    id: 12,
    slug: 'wool-blend-overcoat',
    name: 'Wool Blend Overcoat',
    brand: 'FASHION STORE',
    price: 7999,
    originalPrice: 12999,
    discount: 38,
    category: 'jackets',
    description: 'Sophisticated wool-blend overcoat with a tailored silhouette. Features a notch lapel, double-breasted button closure, and side pockets.',
    images: [
      placeholderImage(600, 800, 'Overcoat+1'),
      placeholderImage(600, 800, 'Overcoat+2'),
      placeholderImage(600, 800, 'Overcoat+3'),
    ],
    colors: [
      { name: 'Camel', hex: '#C19A6B' },
      { name: 'Charcoal', hex: '#36454F' },
      { name: 'Black', hex: '#0A0A0A' },
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    unavailableSizes: ['S'],
    fabric: '70% Wool, 30% Polyester',
    rating: 4.9,
    reviewCount: 34,
    badges: ['bestseller'],
    isNew: false,
    isTrending: true,
  },
];

export const categories = [
  { id: 1, name: 'Shirts', slug: 'shirts', count: 156, image: placeholderImage(600, 750, 'Shirts') },
  { id: 2, name: 'T-Shirts', slug: 't-shirts', count: 89, image: placeholderImage(600, 750, 'T-Shirts') },
  { id: 3, name: 'Trousers', slug: 'trousers', count: 112, image: placeholderImage(600, 750, 'Trousers') },
  { id: 4, name: 'Jackets', slug: 'jackets', count: 67, image: placeholderImage(600, 750, 'Jackets') },
  { id: 5, name: 'Shorts', slug: 'shorts', count: 43, image: placeholderImage(600, 750, 'Shorts') },
  { id: 6, name: 'Polo', slug: 'polo', count: 38, image: placeholderImage(600, 750, 'Polo') },
];

export const collections = [
  {
    id: 1,
    name: 'Summer Essentials',
    slug: 'summer-essentials',
    description: 'Lightweight fabrics and breezy styles for the warmest days.',
    image: placeholderImage(1200, 600, 'Summer+Collection'),
  },
  {
    id: 2,
    name: 'Workwear Edit',
    slug: 'workwear-edit',
    description: 'Sharp, polished pieces that take you from boardroom to bar.',
    image: placeholderImage(1200, 600, 'Workwear+Collection'),
  },
  {
    id: 3,
    name: 'Street Style',
    slug: 'street-style',
    description: 'Bold, urban-inspired looks for the style-forward individual.',
    image: placeholderImage(1200, 600, 'Street+Style'),
  },
];

export const reviews = [
  { id: 1, productId: 1, user: 'Rahul M.', rating: 5, title: 'Perfect fit!', comment: 'The quality is amazing for this price. Fits true to size and the fabric feels premium.', date: '2026-01-15', verified: true },
  { id: 2, productId: 1, user: 'Priya S.', rating: 4, title: 'Great shirt, slight color difference', comment: 'Love the shirt overall. The color was slightly different from the photos but still looks great.', date: '2026-01-10', verified: true },
  { id: 3, productId: 1, user: 'Amit K.', rating: 5, title: 'Best oxford I own', comment: 'This is now my favorite shirt. The material is breathable and wrinkle-resistant.', date: '2026-01-05', verified: false },
  { id: 4, productId: 3, user: 'Sneha R.', rating: 5, title: 'Love the oversized fit', comment: 'Exactly what I was looking for. The graphic print is sharp and the cotton is super soft.', date: '2026-01-20', verified: true },
  { id: 5, productId: 4, user: 'Vikram T.', rating: 4, title: 'Impressive jacket', comment: 'Looks and feels like real leather. Only giving 4 stars because the sleeves are a bit long.', date: '2026-01-18', verified: true },
];

export const heroSlides = [
  {
    id: 1,
    tag: 'New Collection',
    title: 'Urban Stories',
    description: 'City vibes meet comfort.',
    image: placeholderImage(800, 1200, 'Urban+Stories'),
    cta: 'Shop Now',
    link: '/products',
  },
  {
    id: 2,
    tag: 'Limited Edition',
    title: 'Monochrome',
    description: 'Black and white essentials.',
    image: placeholderImage(800, 1200, 'Monochrome'),
    cta: 'Explore',
    link: '/products',
  },
  {
    id: 3,
    tag: 'Sale',
    title: 'Summer Sale',
    description: 'Up to 50% off.',
    image: placeholderImage(800, 1200, 'Summer+Sale'),
    cta: 'Shop Sale',
    link: '/products',
  },
  {
    id: 4,
    tag: 'Trending',
    title: 'Denim Days',
    description: 'Timeless denim styles.',
    image: placeholderImage(800, 1200, 'Denim+Days'),
    cta: 'View All',
    link: '/products',
  },
  {
    id: 5,
    tag: 'New Drop',
    title: 'Athleisure',
    description: 'Performance meets style.',
    image: placeholderImage(800, 1200, 'Athleisure'),
    cta: 'Shop Now',
    link: '/products',
  },
  {
    id: 6,
    tag: 'Exclusive',
    title: 'Party Edit',
    description: 'Stand out tonight.',
    image: placeholderImage(800, 1200, 'Party+Edit'),
    cta: 'Shop Now',
    link: '/products',
  },
];

export const cartItems = [
  {
    id: 1,
    product: products[0],
    size: 'M',
    color: 'White',
    quantity: 1,
  },
  {
    id: 2,
    product: products[3],
    size: 'L',
    color: 'Black',
    quantity: 1,
  },
  {
    id: 3,
    product: products[2],
    size: 'L',
    color: 'Black',
    quantity: 2,
  },
];

export const orders = [
  {
    id: 'ORD-2026-001',
    date: '2026-02-10',
    total: 7898,
    status: 'shipped',
    items: [
      { product: products[0], size: 'M', color: 'White', quantity: 1, price: 1999 },
      { product: products[3], size: 'L', color: 'Black', quantity: 1, price: 5999 },
    ],
    timeline: [
      { status: 'Order Placed', time: 'Feb 10, 2026 — 10:30 AM', completed: true },
      { status: 'Order Confirmed', time: 'Feb 10, 2026 — 11:00 AM', completed: true },
      { status: 'Shipped', time: 'Feb 11, 2026 — 2:15 PM', completed: true, current: true },
      { status: 'Out for Delivery', time: 'Expected: Feb 13, 2026', completed: false },
      { status: 'Delivered', time: '', completed: false },
    ],
    address: {
      name: 'Rahul Sharma',
      street: '42, MG Road, Block B',
      city: 'Bangalore',
      state: 'Karnataka',
      pin: '560001',
      phone: '+91 98765 43210',
    },
  },
];

export const formatPrice = (price) => {
  return `₹${price.toLocaleString('en-IN')}`;
};

export const sizeGuide = {
  headers: ['Size', 'Chest (in)', 'Waist (in)', 'Length (in)'],
  rows: [
    ['XS', '36', '30', '26'],
    ['S', '38', '32', '27'],
    ['M', '40', '34', '28'],
    ['L', '42', '36', '29'],
    ['XL', '44', '38', '30'],
    ['XXL', '46', '40', '31'],
  ],
};
